server:
  AppName: blog-service-1
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

Nacos:
  IpAddr: 8.140.44.29
  Port: 8848
  NamespaceId: public
  Group: DEFAULT_GROUP
  DataId: blog-service


App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log

Database:
  DbType: mysql
  UserName: root
  PassWord: 123456
  Host: 8.140.44.29:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

Host:
  OrderHost: localhost:8001